In [1]:
! git pull

Merge made by the 'ort' strategy.
 a_list.npy | Bin 238160 -> 317512 bytes
 o_list.npy | Bin 14877128 -> 19836628 bytes
 2 files changed, 0 insertions(+), 0 deletions(-)


From github.com:CristianMorasso/XaiProject
   ae7e00b..2bf8772  main       -> origin/main


In [2]:
import pandas as pd
import numpy as np

In [3]:
a = np.load("a_list.npy", allow_pickle=True)
o = np.load("o_list.npy", allow_pickle=True)
o.shape

(39673, 125)

In [4]:
obs = np.zeros((o.shape[0],25,5))
act = np.zeros(a.shape[0])
print(obs.shape)
for i, el in enumerate(o):
    # print(el[0].shape, el0)
    
    obs[i,:,:] = el.reshape(25,5)

(39673, 25, 5)


In [28]:
clean_obs = []
for o in obs:
    clean_obs.append(o[np.where(o[:,0] >0.5) ])

In [6]:
# clean_obs[10], obs[10]

In [15]:
np.where( (a.flatten() != 4))

(array([   33,    34,    35, ..., 39641, 39671, 39672], dtype=int64),)

In [29]:
clean_obs 


[array([[ 1.        ,  0.91872239,  0.        ,  0.3125    ,  0.        ],
        [ 1.        ,  0.09411749,  0.        , -0.03478165,  0.        ],
        [ 1.        ,  0.20360167,  0.        , -0.02885623,  0.        ],
        [ 1.        ,  0.3015323 ,  0.        , -0.02838163,  0.        ],
        [ 1.        ,  0.39632928,  0.        , -0.03468986,  0.        ],
        [ 1.        ,  0.5133546 ,  0.        , -0.01996127,  0.        ],
        [ 1.        ,  0.60510105,  0.5       , -0.04965725,  0.        ],
        [ 1.        ,  0.71106535,  0.5       , -0.01802708,  0.        ],
        [ 1.        ,  0.82770205,  0.25      , -0.02530432,  0.        ],
        [ 1.        ,  0.92296451,  0.        , -0.0469334 ,  0.        ]]),
 array([[ 1.        ,  1.        ,  0.        ,  0.26068053,  0.        ],
        [ 1.        ,  0.07766388,  0.09972567, -0.06410848,  0.05351611],
        [ 1.        ,  0.19062251,  0.        , -0.05203675,  0.        ],
        [ 1.        ,  

In [9]:
# for o in clean_obs:
#     print(o[0,3])


In [30]:
clean_obs[0], a[0]

(array([[ 1.        ,  0.91872239,  0.        ,  0.3125    ,  0.        ],
        [ 1.        ,  0.09411749,  0.        , -0.03478165,  0.        ],
        [ 1.        ,  0.20360167,  0.        , -0.02885623,  0.        ],
        [ 1.        ,  0.3015323 ,  0.        , -0.02838163,  0.        ],
        [ 1.        ,  0.39632928,  0.        , -0.03468986,  0.        ],
        [ 1.        ,  0.5133546 ,  0.        , -0.01996127,  0.        ],
        [ 1.        ,  0.60510105,  0.5       , -0.04965725,  0.        ],
        [ 1.        ,  0.71106535,  0.5       , -0.01802708,  0.        ],
        [ 1.        ,  0.82770205,  0.25      , -0.02530432,  0.        ],
        [ 1.        ,  0.92296451,  0.        , -0.0469334 ,  0.        ]]),
 array([4], dtype=int64))

In [45]:
final_list = []
for co, action in zip(clean_obs, a):
    co[:,1] = 
    final_list.append(np.concatenate([co.flatten(), [a[0][0]]]))
    

In [49]:
final_list

[array([ 0.91872239,  0.        ,  0.3125    ,  0.        ,  0.09411749,
         0.        , -0.03478165,  0.        ,  0.20360167,  0.        ,
        -0.02885623,  0.        ,  0.3015323 ,  0.        , -0.02838163,
         0.        ,  0.39632928,  0.        , -0.03468986,  0.        ,
         0.5133546 ,  0.        , -0.01996127,  0.        ,  0.60510105,
         0.5       , -0.04965725,  0.        ,  0.71106535,  0.5       ,
        -0.01802708,  0.        ,  0.82770205,  0.25      , -0.02530432,
         0.        ,  0.92296451,  0.        , -0.0469334 ,  0.        ,
         4.        ]),
 array([ 1.        ,  0.        ,  0.26068053,  0.        ,  0.07766388,
         0.09972567, -0.06410848,  0.05351611,  0.19062251,  0.        ,
        -0.05203675,  0.        ,  0.28777927,  0.16811214, -0.03611624,
         0.0392936 ,  0.38351884,  0.        , -0.032566  ,  0.        ,
         0.51558763,  0.        ,  0.0205038 ,  0.        ,  0.58605015,
         0.6461159 , -0.0439